apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-06-06T16:14:35Z"
  generation: 8
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 6e108330-a98b-47e2-aadf-1de2504454eb
  resourceVersion: "3498283"
  uid: f2d5e94b-6e4b-42c7-9268-a352e1ed5b3f
spec:
  customization:
    addPage: {}
    customLogoFile:
      name: ""
    developerCatalog:
      types:
        state: Enabled
    projectAccess: {}
    quickStarts: {}
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  plugins:
  - gitops-plugin
  - kubevirt-plugin
  - mce
  - monitoring-plugin
  - networking-console-plugin
  - nmstate-console-plugin
  - acm
  providers: {}
  route:
    hostname: ""
    secret:
      name: ""
  unsupportedConfigOverrides: null
status:
  conditions:
  - lastTransitionTime: "2025-06-18T15:01:58Z"
    status: "False"
    type: ConsoleNotificationSyncDegraded
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: ConsoleNotificationSyncProgressing
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: OIDCClientConfigDegraded
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: OIDCClientConfigProgressing
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: AuthStatusHandlerDegraded
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: AuthStatusHandlerProgressing
  - lastTransitionTime: "2025-06-07T14:37:23Z"
    status: "False"
    type: PDBSyncDegraded
  - lastTransitionTime: "2025-06-06T16:18:56Z"
    status: "False"
    type: PDBSyncProgressing
  - lastTransitionTime: "2025-06-10T17:51:57Z"
    reason: AsExpected
    status: "False"
    type: OAuthClientsControllerDegraded
  - lastTransitionTime: "2025-06-06T16:21:55Z"
    status: "False"
    type: RouteHealthProgressing
  - lastTransitionTime: "2025-06-06T16:25:26Z"
    status: "True"
    type: RouteHealthAvailable
  - lastTransitionTime: "2025-06-06T16:25:26Z"
    status: "False"
    type: RouteHealthDegraded
  - lastTransitionTime: "2025-06-06T16:22:02Z"
    status: "False"
    type: ResourceSyncControllerDegraded
  - lastTransitionTime: "2025-06-06T16:22:02Z"
    status: "False"
    type: CLIAuthStatusHandlerDegraded
  - lastTransitionTime: "2025-06-06T16:22:02Z"
    status: "False"
    type: CLIAuthStatusHandlerProgressing
  - lastTransitionTime: "2025-06-06T16:22:02Z"
    status: "False"
    type: CLIOIDCClientStatusDegraded
  - lastTransitionTime: "2025-06-06T16:22:02Z"
    status: "False"
    type: CLIOIDCClientStatusProgressing
  - lastTransitionTime: "2025-06-06T16:22:03Z"
    status: "False"
    type: ManagementStateDegraded
  - lastTransitionTime: "2025-06-06T16:22:04Z"
    status: "False"
    type: OAuthClientSecretSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:04Z"
    status: "False"
    type: OAuthClientSecretSyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:04Z"
    reason: NoUnsupportedConfigOverrides
    status: "True"
    type: UnsupportedConfigOverridesUpgradeable
  - lastTransitionTime: "2025-06-06T16:22:09Z"
    status: "False"
    type: DownloadsDeploymentSyncProgressing
  - lastTransitionTime: "2025-06-18T15:02:01Z"
    status: "False"
    type: DownloadsDeploymentSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:09Z"
    status: "False"
    type: ServiceSyncProgressing
  - lastTransitionTime: "2025-06-18T15:02:04Z"
    status: "False"
    type: ServiceSyncDegraded
  - lastTransitionTime: "2025-06-10T17:51:57Z"
    status: "False"
    type: OCDownloadsSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:17Z"
    status: "False"
    type: RedirectServiceSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:17Z"
    status: "False"
    type: RedirectServiceSyncProgressing
  - lastTransitionTime: "2025-06-10T18:08:28Z"
    status: "False"
    type: DownloadsCustomRouteSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:25Z"
    status: "False"
    type: DownloadsCustomRouteSyncProgressing
  - lastTransitionTime: "2025-06-10T18:08:28Z"
    status: "True"
    type: DownloadsCustomRouteSyncUpgradeable
  - lastTransitionTime: "2025-06-10T18:08:28Z"
    status: "False"
    type: ConsoleCustomRouteSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:25Z"
    status: "False"
    type: ConsoleCustomRouteSyncProgressing
  - lastTransitionTime: "2025-06-10T18:08:28Z"
    status: "True"
    type: ConsoleCustomRouteSyncUpgradeable
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: ServiceCASyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: TrustedCASyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: OAuthServingCertValidationDegraded
  - lastTransitionTime: "2025-06-06T18:09:10Z"
    status: "False"
    type: DeploymentSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: DeploymentSyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: ConfigMapSyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: ServiceCASyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: CustomLogoSyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: OAuthClientSecretGetProgressing
  - lastTransitionTime: "2025-06-06T16:23:29Z"
    status: "False"
    type: ConsoleConfigDegraded
  - lastTransitionTime: "2025-06-17T19:44:52Z"
    status: "False"
    type: SyncLoopRefreshProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: TrustedCASyncProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: SyncLoopRefreshDegraded
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: CustomLogoSyncDegraded
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: OAuthServingCertValidationProgressing
  - lastTransitionTime: "2025-06-06T16:22:43Z"
    status: "False"
    type: OAuthClientSecretGetDegraded
  - lastTransitionTime: "2025-06-06T16:25:46Z"
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-06-18T15:02:04Z"
    status: "False"
    type: ConfigMapSyncDegraded
  - lastTransitionTime: "2025-06-10T17:51:57Z"
    status: "False"
    type: OAuthClientSyncDegraded
  - lastTransitionTime: "2025-06-06T16:23:02Z"
    status: "False"
    type: OAuthClientSyncProgressing
  - lastTransitionTime: "2025-06-06T16:23:28Z"
    status: "False"
    type: ConsolePublicConfigMapDegraded
  - lastTransitionTime: "2025-06-06T16:23:35Z"
    status: "False"
    type: ODODownloadsSyncDegraded
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "False"
    type: DownloadsDefaultRouteSyncDegraded
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "False"
    type: DownloadsDefaultRouteSyncProgressing
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "True"
    type: DownloadsDefaultRouteSyncUpgradeable
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "False"
    type: ConsoleDefaultRouteSyncDegraded
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "False"
    type: ConsoleDefaultRouteSyncProgressing
  - lastTransitionTime: "2025-06-06T16:23:38Z"
    status: "True"
    type: ConsoleDefaultRouteSyncUpgradeable
  generations:
  - group: apps
    hash: ""
    lastGeneration: 2
    name: downloads
    namespace: openshift-console
    resource: deployments
  - group: apps
    hash: ""
    lastGeneration: 11
    name: console
    namespace: openshift-console
    resource: deployments
  observedGeneration: 8
  readyReplicas: 1
