apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  creationTimestamp: "2025-06-03T19:22:55Z"
  finalizers:
  - imageregistry.operator.openshift.io/finalizer
  generation: 7
  name: cluster
  resourceVersion: "92101"
  uid: 41446d57-ffb0-426a-aecc-9b344baa63a4
spec:
  httpSecret: 8d868e206f5131e2691e89c77599b8d31d268e6586486e47e53b2b5cd7a10c10ae6b60414f71c9ce5df36e67851df74a993fd118bf431f5cf581740be5a0721d
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  proxy: {}
  replicas: 1
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  rolloutStrategy: Recreate
  storage:
    managementState: Unmanaged
    pvc:
      claim: image-registry-storage
  unsupportedConfigOverrides: null
